---
apiVersion: v1
kind: Service
metadata:
  name: arango
  namespace: development
  labels:
    app.kubernetes.io/instance: arango
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arango
spec:
  type: {{ .Values.arangodb.serviceType }}
  selector:
    app: arangodb
  ports:
    - name: arangodb
      port: {{ .Values.arangodb.single.servicePort }}
      targetPort: {{ .Values.arangodb.single.servicePort }}
