serverInfo:
    contextPath: /v1/helm
apiVersion: v1
entries:
    jenkins:
    - apiVersion: v2
      appVersion: "1.0"
      description: A Helm chart for jenkins
      name: jenkins
      version: 2.387.1
      urls:
      - https://github.com/frmscoe/helm/tree/main/jenkins
generated: "2023-04-02T19:24:40.5121566+02:00"
