serverInfo:
    contextPath: /v1/helm
apiVersion: v1
entries:
    nginx-ingress:
    - apiVersion: v2
      appVersion: "1.0"
      description: A Helm chart for nginx-ingress
      name: nginx-ingress
      version: 1.6.4
      urls:
      - https://github.com/frmscoe/helm/tree/main/nginx-ingress-controller
generated: "2023-04-02T19:24:40.5121566+02:00"
