serverInfo:
    contextPath: /v1/helm
apiVersion: v1
entries:
    arangodb:
    - apiVersion: v2
      appVersion: "1.0"
      description: A Helm chart for arangodb
      name: arangodb
      version: latest
      urls:
      - https://github.com/frmscoe/helm/tree/main/arangodb-single
generated: "2023-04-02T19:24:40.5121566+02:00"
