apiVersion: v1
appVersion: 8.5.1
description: Official Elastic helm chart for Elastic APM Server
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/apm.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: apm-server
sources:
- https://github.com/elastic/apm
version: 8.5.1
