serverInfo:
    contextPath: /v1/helm
apiVersion: v1
entries:
    openfaas:
    - apiVersion: v2
      appVersion: "1.0"
      description: A Helm chart for openfaas
      name: openfaas
      version: 12.0.2
      urls:
      - https://github.com/frmscoe/helm/tree/main/openfaas
generated: "2023-04-02T19:24:40.5121566+02:00"
